### ISSUE TITLE
"mode" aggregation function panics 

### ISSUE THREAD

**Issue by vi** [maxblee/clipivot#4]
```
thread 'main' panicked at 'internal error: entered unreachable code', /home/vi/.cargo/registry/src/-3d9d141e372ea94e/clipivot-0.3.4/src/main.rs:293:14
```

Maybe caused by empty values.

Also "repository" field in `Cargo.toml` is not filled in, complicating filing issues for the project.

**Comment by maxblee** [comment]
Thanks. I refactored the code that handles the different aggregation functions and failed to copy over the mode function. Added regression tests and put the mode back in; should be fixed now (as should the repository field).
